<?php
/* $Id: inclind_cdn.module,v 1.0 2008/11/13 12:30:00 pete@inclind.com Exp $ */

function inclind_cdn_css_path_rewrite($data) {
	$final_data = preg_replace('/url\(\/(sites\/all\/themes|misc)/', 'url(' . variable_get('inclind_cdn_css_path', '') . '/\1', $data);
	return $final_data;
}


/**
 * Implementation of hook_help().
 */
function inclind_cdn_help($path, $arg) {
  switch ($path) {
    case 'admin/help#inclind_cdn':
      return t('inclind_cdn - node auto term');
  }
}

/**
 * Implementation of hook_menu().
 */
function inclind_cdn_menu() {
  $items = array();

  $items['admin/settings/inclind_cdn'] = array(
    'title' => t('Inclind CDN'),
    'description' => t('Configure CDN settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('inclind_cdn_settings_form'),
    'access arguments' => array('administer nodes')
  );
  return $items;
}



/**
 * Menu callback: inclind_cdn module settings form.
 */
function inclind_cdn_settings_form() {
    $form['inclind_cdn_css_path'] = array(
      '#type' => 'textfield',
      '#title' => 'Path for CSS files',
      '#default_value' => variable_get('inclind_cdn_css_path', '')
    );
  $form['submit'] = array('#type' => 'submit', '#value' => t('Save configuration'));

  return $form;
}


/**
 * Process inclind_cdn settings form submissions.
 */
function inclind_cdn_settings_form_submit($form, &$form_state) {
  $form_values = $form_state['values'];

  variable_set('inclind_cdn_css_path', $form_values['inclind_cdn_css_path']);
}

