<?php
// $Id: image_cycle.module,v 1.2 2008/12/29 22:36:42 boombatower Exp $
/**
 * @file
 * Create an image slideshow from images in a gallery using the jQuery Cycle plugin.
 *
 * Copyright 2008 by Jimmy Berry ("boombatower", http://drupal.org/user/214218)
 */

/**
 * Implementation of hook_menu().
 */
function image_cycle_menu() {
  $items = array();

  $items['image_cycle/%'] = array(
    'title' => 'Image slideshow',
    'page callback' => 'image_cycle_show',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );

  return $items;
}

/**
 * Implementation of hook_theme().
 */
function image_cycle_theme() {
  return array(
    'image_cycle_cycle' => array(
      'arguments' => array(
        'images' => NULL,
        'effect' => 'fade',
        'parameters' => array(),
      ),
    ),
  );
};

/**
 * Implementation of hook_form_alter().
 */
function image_cycle_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'image_gallery_admin_form') {
    $form['#submit'][] = 'image_cycle_gallery_submit';
    $form['image_cycle'] = array(
      '#type' => 'fieldset',
      '#title' => t('Cycle settings'),
      '#description' => t('The JQuery Cycle effect to use when displaying slideshow with the Image slideshow module. ' .
                           '(<a href="http://malsup.com/jquery/cycle/">effects preview</a>)'),
      '#tree' => TRUE
    );
    if ($form['tid']['#value']) {
      $form['image_cycle']['view'] = array(
        '#type' => 'item',
        '#title' => t('View'),
        '#value' => l('image_cycle/' . $form['tid']['#value'], 'image_cycle/' . $form['tid']['#value'])
      );
    }
    $form['image_cycle']['effect'] = array(
      '#type' => 'select',
      '#title' => t('Effect'),
      '#options' => array(
        'blindX',
        'blindY',
        'blindZ',
        'cover',
        'curtainX',
        'curtainY',
        'fade',
        'fadeZoom',
        'growX',
        'growY',
        'scrollUp',
        'scrollDown',
        'scrollLeft',
        'scrollRight',
        'scrollHorz',
        'scrollVert',
        'shuffle',
        'slideX',
        'slideY',
        'toss',
        'turnUp',
        'turnDown',
        'turnLeft',
        'turnRight',
        'uncover',
        'wipe',
        'zoom',
      ),
      '#default_value' => variable_get('image_cycle_effect_' . $form['vid']['#value'], 'fade')
    );
    $form['image_cycle']['effect']['#options'] = drupal_map_assoc($form['image_cycle']['effect']['#options']);
    $form['image_cycle']['parameters'] = array(
      '#type' => 'textarea',
      '#title' => t('Parameters'),
      '#description' => t('Custom parameters to pass with the effect. Place each parameter on a line in the format KEY:VALUE.' .
                          'Leave blank for default effect settings.'),
      '#default_value' => implode("\n", variable_get('image_cycle_parameters_' . $form['vid']['#value'], array()))
    );
    $form['image_cycle']['css'] = array(
      '#type' => 'textarea',
      '#title' => t('CSS'),
      '#description' => t('Custom CSS for the slideshow. The images will be encapsulated by <em>image_cycle_pictures</em>.'),
      '#default_value' => variable_get('image_cycle_css_' . $form['vid']['#value'], '')
    );
  }
}

/**
 * Submit callback for gallery taxonmy form.
 */
function image_cycle_gallery_submit($form, &$form_state) {
  variable_set('image_cycle_effect_' . $form_state['values']['vid'], $form_state['values']['image_cycle']['effect']);
  variable_set('image_cycle_parameters_' . $form_state['values']['vid'], explode("\n", $form_state['values']['image_cycle']['parameters']));
  variable_set('image_cycle_css_' . $form_state['values']['vid'], $form_state['values']['image_cycle']['css']);
}

/**
 * Display a slideshow for the specified term ID.
 *
 * @param interger $tid Term ID.
 * @return string HTML output.
 */
function image_cycle_show($tid) {
  $term = taxonomy_get_term($tid);
  $images = image_cycle_get_images($tid);
	
  $effect = variable_get('image_cycle_effect_' . $term->vid, 'fade');
  $parameters = variable_get('image_cycle_parameters_' . $term->vid, array());
  $css = variable_get('image_cycle_css_' . $term->vid, '');

  $out = '';
//  drupal_set_title($term->name); TODO
  if ($images) { drupal_add_js(drupal_get_path('module', 'image_cycle') . '/jquery.cycle.js'); }
  
  if ($css) {
    $out .= '<style>' . $css . '</style>';
  }
  if ($images) {
    return $out . theme('image_cycle_cycle', $images, $effect, $parameters);
  }
  return t('No images');
}

/**
 * Theme an image cycle for a set of images.
 *
 * @param array $images Set of images to include in the cycle.
 * @param string $effect Effect method.
 * @param array $parameters Associative array of parameters for cycle effect.
 * @param string $id The HTML id to use for the container. Default: slide-#.
 * @return string HTML output.
 */
function theme_image_cycle_cycle($images, $effect = 'fade', $parameters = array(), $id = NULL) {
  static $count = 0;
 
 if (count($images) > 1) {
 	  $parameters['fx'] = "'$effect'";
	
	  // Create JSON output.
	  $json = array();
	  foreach ($parameters as $key => $value) {
		if (!is_numeric($key)) {
		  $json[] .= "$key: $value";
		}
	  }
	
	  if (!$id) {
		$id = "slide-$count";
	  }
	
	  drupal_add_js("$('#$id').cycle({" . implode(', ', $json) . "});", 'inline', 'footer');
	  $out = '<div id="' . $id . '" class="image_cycle_pictures">';
	  $showCount = 0;
	  foreach ($images as $image) {
	  	$showID = "show-".$showCount;
	  	$out .= '<div id="' . $showID . '">';
		if (($image->field_link)) {
			foreach ($image->field_link as $url) {
				$imageLink = '';
				
				if (preg_match('/http:\/\//', $url['url']) && strlen($url['url'])) {
					$url = '<a href="'.$url['url'].'" target="_blank">';
				} elseif (!(preg_match('/http:\/\//', $url['url'])) && strlen($url['url'])) {
					$imageLink = '<a href="/'.$url['url'].'">';
				}
			}
		}
		
		if (function_exists("inclind_banner_image_display")) {
			if (strlen($imageLink)) {
				$out .= $imageLink.inclind_banner_image_display($image).'</a>';
			} else {
					$out .= inclind_banner_image_display($image);
			}
		}
		
		$out .= '<div class="bannerInformation"><div class="shadow"><h2 class="bannerTitle">'.$image->title.'</h2> <div class="bannerBody">'.$image->body.'</div></div></div>';
		$out .= '</div>';
		$showCount++;
	  }
	  $out .= '</div>';
	  $count++;
	  return $out;
  } else {
	  if (!$id) {
		$id = "slide-$count";
	  }
	
	  $out = '<div id="' . $id . '" class="image_cycle_pictures">';
	  foreach ($images as $image) {
		if (($image->field_link)) {
			foreach ($image->field_link as $url) {
				$imageLink = '';
				
				if (preg_match('/http:\/\//', $url['url']) && strlen($url['url'])) {
					$imageLink = '<a href="'.$url['url'].'" target="_blank">';
				} elseif (!(preg_match('/http:\/\//', $url['url'])) && strlen($url['url'])) {
					$imageLink = '<a href="/'.$url['url'].'">';
				}
			}
		}
		
		if (function_exists("inclind_banner_image_display")) {
			if (strlen($imageLink)) {
				$out .= $imageLink.inclind_banner_image_display($image).'</a>';
			} else {
				$out .= inclind_banner_image_display($image);
			}
		}

		$out .= '<div class="bannerInformation"><div class="shadow"><h2 class="bannerTitle">'.$image->title.'</h2> <div class="bannerBody">'.$image->body.'</div></div></div>';
	  }

	  $out .= '</div>';
	  return $out;  
  }
}

/**
 * Get the set of images in the specified term ID. Copied from
 * image_gallery.module:image_gallery_page().
 *
 * @param integer $tid Term Id.
 * @return array List of node objects contained by term ID that contain images.
 */
function image_cycle_get_images($tid) {
  // Allow images to be sorted in a useful order.
  $query = "SELECT n.nid, cti.field_link_url FROM {term_node} t INNER JOIN {node} n ON t.nid = n.nid LEFT JOIN {content_type_image} cti ON cti.nid = n.nid WHERE n.status = 1 AND n.type = 'image' AND t.tid = %d ";
  $count_query = "SELECT COUNT(DISTINCT(n.nid)) FROM {term_node} t INNER JOIN {node} n ON t.nid = n.nid WHERE n.status = 1 AND n.type = 'image' AND t.tid = %d ";
  $args = array($tid);
  switch (variable_get('image_gallery_sort_order', IMAGE_GALLERY_SORT_CREATE_DESC)) {
    case IMAGE_GALLERY_SORT_CREATE_DESC:
      $query .= 'ORDER BY n.sticky DESC, n.created DESC';
      $args[] = IMAGE_ORIGINAL;
	  break;

    case IMAGE_GALLERY_SORT_CREATE_ASC:
      $query .= 'ORDER BY n.sticky DESC, n.created ASC';
	  $args[] = IMAGE_ORIGINAL;
      break;

    case IMAGE_GALLERY_SORT_FILENAME:
      $query = "SELECT n.nid FROM {term_node} t INNER JOIN {node} n ON t.nid = n.nid
        INNER JOIN {image} i ON n.nid = i.nid INNER JOIN {files} f ON i.fid = f.fid
        WHERE n.status = 1 AND i.image_size = '_original' AND n.type = 'image' AND t.tid = %d AND f.filename = '%s'
        ORDER BY n.sticky DESC, f.filepath";
      $args[] = IMAGE_ORIGINAL;
      break;

    case IMAGE_GALLERY_SORT_TITLE:
      $query .= 'ORDER BY n.sticky DESC, n.title ASC';
	  $args[] = IMAGE_ORIGINAL;
      break;
  }
  $result = pager_query(db_rewrite_sql($query), variable_get('image_images_per_page', 6), 0, db_rewrite_sql($count_query), $args);
  
  while ($node = db_fetch_object($result)) {
    $images[] = node_load(array('nid' => $node->nid));
  }
  
  return $images;
}
